name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a0b380ad33ec1abd8c3ea2d20eaa1f355fb4a603a1b5df0e1dacc8b00bbaa22"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
