name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00e3a3f8cf31d81da89424493e0f52dda831e04a5408f8ee800d83f0ec4fab49"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
