name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e77b7b72e0ae2a91dd504b618424158d79e885aba5eacc0cc892a47f85202865"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
