name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0344563edc602a805d9d17b14358775483c9c71631ff4488afbef1cbd4c4cee9"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
