name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26759196a5db608dde79d8bc67058b4a511236e7fd7c2e5cf218bac05ed702e6"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
