name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a21a620748b25fcd8638678fa9e3c7286f81473d056f3e16c0f9afc201866ca1"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
