name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42053a455cd040808edba1e4b6b860476a2502ff8b87da41efc89d804713ad5e"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
