name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddc1956797a330a49d331ffd3f1b86584fb8d999c72e69cc543e22fab17cd6cb"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
