name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7a5fbcfed4852c1388e70ecabcadc49d31d527d947d3bd8c566b7301c401573"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
