name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1143837a5a58c0f8c6d43b599160b3c51752c66eea66c064932097ceda5b3442"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
