name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55514e763a2c70be061ac8d9bc7416feebcdba2e51de184afcfb52d496f6d247"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
