name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38d6acb4ff0aafdb29521980df708cc83312891b8054b30bcdc9104ecfcb7b60"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
