name = "KSMP"
author = "kams"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "097f64f323d15ab5b1ca3b5d41c86b0cc88828584fa24bd99f1e658db1b9195e"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
